# Generated by Django 3.1.5 on 2021-01-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Token_auth',
        ),
    ]
